src/WebConfig/urls.py
# Copyright 2015–2020 Kullo GmbH
#
# This source code is licensed under the 3-clause BSD license. See LICENSE.txt
# in the root directory of this source tree for details.
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

import account.urls
import account.views
import notifications.urls


urlpatterns = [
    # Examples:
    # url(r'^$', 'WebConfig.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^login/$', account.views.login, name='login',
        kwargs={'redirect': 'account:index'}),
    url(r'^logout/$', account.views.logout, name='logout',
        kwargs={'redirect': 'account:loggedout'}),

    url(r'^status$', account.views.status, name='status'),

    url(r'^account/', include(account.urls, namespace='account')),
    url(r'^notifications/', include(notifications.urls, namespace='notifications')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/account/urls.py
# Copyright 2015–2020 Kullo GmbH
#
# This source code is licensed under the 3-clause BSD license. See LICENSE.txt
# in the root directory of this source tree for details.
from django.conf.urls import url

from . import views

app_name = 'account'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^loggedout/$', views.loggedout, name='loggedout'),
]

src/templates/base.html
{% load compile_static %}
{% load i18n %}
{% load static %}
{% load tags %}
<!DOCTYPE html>
<html>
<head>

    <title>{% block title %}{% endblock %} - Kullo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'WebConfig/global.less'|compile %}" />

	{% block javascripts %}
	{% endblock %}

</head>
<body>
<div class="page">
    {% if user.is_authenticated %}

    {% url 'account:index' as account %}
    {% url 'notifications:index' as notifications %}
    <div class="menubar">
        <ul id="menu">
            <li class="{% active account %}">
                <a class="menuentry" href="{{ account }}">{% trans "Account" %}</a>
            </li>
            <li class="{% active notifications %}">
                <a class="menuentry" href="{{ notifications }}">{% trans "Notifications" %}</a>
            </li>
        </ul>

        <a id="logout" class="button" href="{% url 'logout' %}">{% trans "Logout" %}</a>
    </div>
    {% endif %}

	{% if messages %}
	<ul class="messages">
		{% for message in messages %}
		<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{message}}</li>
		{% endfor %}
	</ul>
	{% endif %}

	{% block content %}
	{% endblock %}
</div><!-- .page -->
</body>
</html>